<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Rohit" name="Test1" tests="3" failures="2" timestamp="10 Aug 2019 08:49:04 GMT" time="0.063" errors="0">
  <testcase name="test1" time="0.013" classname="PriorityDemo.TestNGRetryFailedDemo"/>
  <testcase name="test2" time="0.004" classname="PriorityDemo.TestNGRetryFailedDemo">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at PriorityDemo.TestNGRetryFailedDemo.test2(TestNGRetryFailedDemo.java:18)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.004" classname="PriorityDemo.TestNGRetryFailedDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at PriorityDemo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:24)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test1 -->
